services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  app:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11957557-assessment1-repo:latest
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_SECRET: ${APP_SECRET}
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "3000:3000"

volumes:
  dbdata:
