services:

  app:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/group101-assessment2-repo:latest

    environment:
      USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      CLIENT_ID: ${COGNITO_CLIENT_ID}
      CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      AWS_REGION: ap-southeast-2
      S3_BUCKET: n11957557-video-bucket
      DDB_TABLE_FILES: n11957557-videos
      DDB_TABLE_TASKS: n11957557-tasks
      QUT_USERNAME: n11957557@qut.edu.au
    ports:
      - "3000:3000"
"
